"""Add homepage_url to Journal

Revision ID: 53341bd9a231
Revises: 680a75a754e2
Create Date: 2024-01-07 22:16:07.901388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '53341bd9a231'
down_revision: Union[str, None] = '680a75a754e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('homepage_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'homepage_url')
    # ### end Alembic commands ###
